[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Serializable request and response types for the Matrix client API."
documentation = "https://docs.rs/ruma-client-api"
homepage = "https://github.com/ruma/ruma-client-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client-api"
version = "0.1.0"

[dependencies]
futures = "0.1.14"
hyper = "0.11"
ruma-events = "0.9.0"
ruma-identifiers = "0.11.0"
ruma-signatures = "0.4.0"
serde = "1.0.2"
serde_derive = "1.0.2"
serde_json = "1.0.1"
serde_urlencoded = "0.5.1"
url = "1.5.1"

[dependencies.ruma-api]
git = "https://github.com/jplatte/ruma-api"

[dependencies.ruma-api-macros]
git = "https://github.com/jplatte/ruma-api-macros"
branch = "spike"
